"""Generate notes/RUN_IN_TARGET.md — the manifest of every RUN-IN-TARGET cell.

Scanning conventions are shared with the honesty audit: ``RIT_RE`` and
``audit_series`` are imported from ``tools/honesty_audit.py`` (itself the
promotion of NB17 §8), so the manifest's row count reconciles exactly — by
construction, and re-verified on every run — with the audit's RUN-IN-TARGET
total and with the registered ``honesty_audit`` artifact.

Each row records: the notebook, the placard's ``mac``/``node`` label, the
notebook's nearest preceding markdown heading as section context, and the
placard's first comment line (verbatim, minus the placard tag) as its one-line
description. Matches of the shared regex that are textual references *inside*
a cell's code (strings documenting the convention) rather than placard comment
lines are kept — the audit counts them identically — but marked as such.

Usage:
    uv run python tools/gen_run_in_target.py [--root PATH] [--out PATH]
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

# Shared scanning conventions — the import guarantees regex lockstep with the audit.
from honesty_audit import RIT_RE, audit_series

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*\S)")

REFERENCE_DESC = (
    "*(in-code reference: the shared audit regex matches this text inside the "
    "cell's source; not itself a tier-gated placard cell)*"
)


@dataclass
class Row:
    notebook: str
    label: str
    section: str
    description: str
    is_placard: bool


def scan_notebook(path: Path) -> list[Row]:
    """Manifest rows for one executed notebook, in cell order."""
    nb_json = json.loads(path.read_text())
    section = "(before first heading)"
    rows: list[Row] = []
    for cell in nb_json["cells"]:
        src = "".join(cell["source"])
        if cell["cell_type"] == "markdown":
            for line in src.splitlines():
                heading = HEADING_RE.match(line)
                if heading:
                    section = heading.group(2).strip()
            continue
        if cell["cell_type"] != "code":
            continue
        for match in RIT_RE.finditer(src):
            line_start = src.rfind("\n", 0, match.start()) + 1
            line_end = src.find("\n", match.end())
            line_end = len(src) if line_end == -1 else line_end
            # A genuine placard is a comment line: nothing but whitespace precedes
            # the '#' of the match on its line. Anything else is an in-code
            # reference the shared regex counts identically.
            is_placard = src[line_start : match.start()].strip() == ""
            description = (
                src[match.end() : line_end].strip() if is_placard else REFERENCE_DESC
            )
            rows.append(
                Row(
                    notebook=path.name,
                    label=match.group(1).strip(),
                    section=section,
                    description=description or "(empty placard line)",
                    is_placard=is_placard,
                )
            )
    return rows


def _esc(text: str) -> str:
    """Escape the markdown table delimiter (e.g. the `mac|node` label)."""
    return text.replace("|", "\\|")


def render(rows: list[Row], audit_rit_total: int) -> str:
    placards = [r for r in rows if r.is_placard]
    references = [r for r in rows if not r.is_placard]
    label_counts = Counter(r.label for r in placards)
    # No pipe-escaping here: this lands in a prose paragraph, where a code span
    # keeps its pipe verbatim (escaping is only needed inside table cells).
    label_summary = ", ".join(f"{n} `{lbl}`" for lbl, n in sorted(label_counts.items()))
    lines = [
        "# RUN-IN-TARGET — the heavy-cell manifest",
        "",
        "*Generated by `tools/gen_run_in_target.py` — do not edit by hand; regenerate with",
        "`uv run python tools/gen_run_in_target.py`. The scanner shares its regex with",
        "`tools/honesty_audit.py` (NB17 §8 promoted to a repo tool), so the row count below",
        "reconciles exactly with the audit's RUN-IN-TARGET total.*",
        "",
        "**The tier rail.** A `# [RUN-IN-TARGET mac|node]` cell is real tier-gated code, and",
        "the tier only ever arrives through config (`run.tier`): the definitive run is the",
        "SAME cell at `tier=target` (or `mid`) — one code path, no forked heavy-run logic",
        "anywhere (PLAN §2). At smoke tier, where the heavy run does not fit, the cell",
        "prints a placard saying what it computes and where its real run belongs — instead",
        "of pretending.",
        "",
        "**Where the heavy runs go (hardware locked at sign-off — BUILD_STATE).** The policy",
        "is **mac-first**: every cell that fits the Mac runs there. `mac` = the lab's M2 Max,",
        "96 GB unified memory, MPS (tier `mid`). `node` = ONE 4×A100 80 GB / 900 GB RAM /",
        "90-core machine (tier `target`) — **the hard ceiling**: nothing in the lab may",
        "exceed this single node, and there are no cluster code paths. A `mac|node` label",
        "marks a ladder cell with rungs on both machines (mid on the mac, target on the",
        "node). Smoke — the 4-CPU/15 GB container — runs the whole series live at 1e5–1e6;",
        "`analytical` is 1e8–1e9 extrapolation only.",
        "",
        f"**Accounting.** {len(rows)} rows — one per match of the shared placard regex over",
        "the executed notebooks' code cells, equal to the honesty audit's RUN-IN-TARGET",
        f"total ({audit_rit_total}, re-verified at generation time): {len(placards)} genuine",
        f"placard cells ({label_summary}) plus {len(references)} in-code textual references",
        "to the placard convention (strings inside cells that document or annotate it),",
        "which the shared regex counts identically and this manifest therefore keeps —",
        "marked below — rather than drops. Descriptions are each placard's first comment",
        "line, verbatim (wrapped placards break at the source line).",
        "",
        "| Notebook | Label | Section | Placard (first comment line) |",
        "|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r.notebook}` | `{_esc(r.label)}` | {_esc(r.section)} "
            f"| {_esc(r.description)} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repo root holding notebooks/ and notes/ (default: this repo)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="output path (default: <root>/notes/RUN_IN_TARGET.md)",
    )
    args = parser.parse_args(argv)
    root = args.root.resolve()
    out = args.out if args.out is not None else root / "notes" / "RUN_IN_TARGET.md"

    rows: list[Row] = []
    for path in sorted((root / "notebooks").glob("*.ipynb")):
        rows.extend(scan_notebook(path))

    # Parity rail: the manifest must count exactly what the audit counts.
    _, totals = audit_series(root)
    if len(rows) != totals["n_rit_cells"]:
        raise SystemExit(
            f"parity failure: manifest has {len(rows)} rows but the honesty audit "
            f"counts {totals['n_rit_cells']} RUN-IN-TARGET matches — the scanners "
            "have drifted apart"
        )

    out.write_text(render(rows, totals["n_rit_cells"]))
    n_placards = sum(r.is_placard for r in rows)
    print(
        f"wrote {out} — {len(rows)} rows ({n_placards} placard cells, "
        f"{len(rows) - n_placards} in-code references); row count equals the "
        f"honesty audit's RUN-IN-TARGET total ({totals['n_rit_cells']})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
